defaults:
  - _self_

num_steps: 20000
eval_steps: 1000
evalulation_interval: 1000
gradient_accumulation: 2
batch_size: 42
log_dir: hdee/experiments/seed_models

train_data_loader:
  _target_: data_loaders.ShardedDataset
  path: hdee/dataset/openwebtext/train/*.parquet

validation_data_loaders:
  dev:
    _target_: data_loaders.ShardedDataset
    path: hdee/dataset/openwebtext/validation/*.parquet

weight_strategy:
  _target_: weight_strategies.UniformStrategyBuilder

optimizer:
  _target_: data_parallel_optimizer.DataParallelOptimizerBuilder
  lr: 6e-4

scheduler:
  _target_: schedulers.CosineWarmupLRBuilder
  min_lr: 6e-5
  max_steps: 20000
  warmup_steps: 1000