defaults:
  - _self_

train_data_loader:
  _target_: data_loaders.ShardedDataset
  path: hdee/dataset/simple_wikipedia_LM/train/*.parquet

validation_data_loaders:
  dev:
    _target_: data_loaders.ShardedDataset
    path: hdee/dataset/simple_wikipedia_LM/validation/*.parquet