defaults:
  - _self_

train_data_loader:
  _target_: data_loaders.ShardedDataset
  path: /home/gensyn/workdir/hdee/dataset/Caselaw_Access_Project/train/*.parquet

validation_data_loaders:
  dev:
    _target_: data_loaders.ShardedDataset
    path: /home/gensyn/workdir/hdee/dataset/Caselaw_Access_Project/validation/*.parquet