defaults:
  - _self_
  - dataset_History_and_events
  - train_domain_hyperparam_lr6e5
  - directory 
  
exp_name: train_iter1_expert_m_domain_History_and_events

model:
  model_dir: /home/gensyn/workdir/hdee/experiments/seed_models/train_seed_expert_m/checkpoints/model_20000.bin

