defaults:
  - _self_
  - dataset_math_l1
  - train_domain_hyperparam_lr6e5
  - directory 

exp_name: train_iter1_expert_l_domain_math_l1

model:
  model_dir: /home/gensyn/workdir/hdee/experiments/seed_models/train_seed_expert_l/checkpoints/model_20000.bin

