defaults:
  - _self_
  - dataset_TinyStories
  - train_domain_hyperparam_lr6e5
  - directory 

exp_name: train_iter3_MHC_PHS_expert_s_domain_TinyStories

model:
  model_dir: /home/gensyn/workdir/hdee/experiments/hdee_3_iterations/train_iter2_MHC_expert_m_domain_simple_wikipedia_LM/checkpoints/model_400.bin


